### ISSUE TITLE
avoid putting auth secrets in notebooks

### ISSUE THREAD

**Issue by soxofaan** [eu-cdse/notebook-samples#13]
sentinel hub notebooks contain auth related snippets like:

```
from sentinelhub import SHConfig

config = SHConfig()
# config.sh_client_id = "<CLIENT ID>"
# config.sh_client_secret = "<CLIENT SECRET>"
config.sh_token_url = "https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token"
config.sh_base_url = "https://sh.dataspace.copernicus.eu"
config.save("cdse")
```

can we avoid tricking users to put their secret in a notebook like this? This leads too easily to leaking secrets (e.g. sharing exported notebooks, going through notebooks in video calls, ...)

e.g. put the secrets in a local config file instead

(related to #12)

**Comment by willrayeo** [comment]
Hi Stefaan,

This cell has now been updated:

```
config = SHConfig()

# config.sh_client_id = "<CLIENT ID>"
# config.sh_client_secret = "<CLIENT SECRET>"
config.sh_token_url = "https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token"
config.sh_base_url = "https://sh.dataspace.copernicus.eu"
config.save("cdse")

# Saved config can be later accessed with config = SHConfig("cdse")

config = SHConfig("cdse")
```
Once the cell has been run, the user will have configured their CDSE credentials for use with Sentinel Hub Python using a profile in their configuration. In future, they only need to use  `config = SHConfig("cdse")` to initiate their configuration. 

If there are further measures we can take, then happy to work together to implement this.

**Comment by soxofaan** [comment]
Hi @willrayeo 

I'm not sure if I understand the improvement. 
It is still suggested to the user to put their secret verbatim and plaintext-readable in a notebook cell. An they still have to manually comment out/delete lines, which is cumbersome and error-prone.

Isn't it possible to do something like this:

```python
if config_not_set_up_yet:
    import getpass
    client_id = getpass.getpass("Enter your SentinelHub client id")
    secret = getpass.getpass("Enter your SentinelHub client secret")
    config = SHConfig()
    ....
    config.save("cdse")
else:
    config = SHConfig("cdse")
```

Then the secrets will not be visible in the notebook and the code will automatically do the right thing (use an existing config if possible and create a new one otherwise)

**Comment by willrayeo** [comment]
Hi @soxofaan 

Thanks for the input, we have made changes to all the notebooks that use Sentinel Hub credentials. I agree that your method is a much better way of doing it.

**Comment by Kampen1988** [comment]
How should we handle the [keycloak token generation Python request](https://documentation.dataspace.copernicus.eu/APIs/Token.html#by-python-script) in code examples in this repo?

Are there any environment credentials for the tests as well?

If we comment out all cells that rely on the keycloak token generated with 
```python
keycloak_token = get_keycloak(
    getpass.getpass("Enter your username"),
    getpass.getpass("Enter your password"),
)
```
this won't be user friendly anymore.

**Comment by soxofaan** [comment]
I'm currently looking into a tool like https://indigo-dc.gitbook.io/oidc-agent/  to take care of token generation and storage, so that we don't have to reinvent the auth token wheel in every example notebook

**Comment by Kampen1988** [comment]
@soxofaan , please let us know when you find a better way for authentication, token generation and alike. Will close the issue for now.
