### ISSUE TITLE
Download Sentinel 1 & 2 data

### ISSUE THREAD

**Issue by ibaris** [eu-cdse/notebook-samples#37]
I just want to download Sentinel 1 and 2 data. Do you guys have a MINIMAL example for that?

**Comment by Pratichhya** [comment]
@ibaris, you can find minimal example using openEO for Sentinel 2 [here](https://documentation.dataspace.copernicus.eu/notebook-samples/openeo/Load_Collection.html) and can similarly replicate for other collections.
