### ISSUE TITLE
mistake in odata_basic.ipynb

### ISSUE THREAD

**Issue by Rapsodia86** [eu-cdse/notebook-samples#49]
Hi,
Thanks for providing an example for downloading selected bands. It would be good to add this to the API documentation of oData (https://documentation.dataspace.copernicus.eu/APIs/OData.html)

In the Download bands part, a filename in the URL is missing:
This is now: `url = f"{catalogue_odata_url}/Products({product_identifier})/Nodes({product_name})/Nodes({band_file[1]})/Nodes({band_file[2]})/Nodes({band_file[3]})/Nodes({band_file[4]})/$value"`
Should be:
`url = f"{catalogue_odata_url}/Products({product_identifier})/Nodes({product_name})/Nodes({band_file[1]})/Nodes({band_file[2]})/Nodes({band_file[3]})/Nodes({band_file[4]})/Nodes({band_file[5]})/$value"`

and then, instead of: 
`outfile = Path.home() / band_file[4]`  
and
`print("Saved:", band_file[4])`

should be:
`outfile = Path.home() / band_file[5]`  
and
`print("Saved:", band_file[5])`

**Comment by KanerLev** [comment]
Dear @Rapsodia86 ,

Thank you for reaching out in here. Per the first part ("It would be good to add this to the API documentation of oData"), thank you for the suggestion as we strive to improve the documentation we appreciate the feedback. It will be evaluated and once/if approved you may see it reflected in the [OData documentation](https://documentation.dataspace.copernicus.eu/APIs/OData.html).

For the second part: the aim was to retrieve bands that's sufficient to create a RGB composite which would require B2, B3, B4 for S2 but for the sake of simplicity though: initially B1, B2, B3, and B4 is retrieved. But later only B2 (blue), B3(green), and B4(red) are used for RGB composite.
Accordingly, looking at above point of view: there was no requirement to add B5 (or "band_file[5])").

Let us know if you have any other/ further feedback.
