### ISSUE TITLE
NDVI timeseries: use netcdf or csv instead of json output format

### ISSUE THREAD

**Issue by jdries** [eu-cdse/notebook-samples#7]
For aggregated timeseries, the json output is custom while csv and netcdf provide more standardized options.
My suggestion would be to use csv in this case, because it is convenient for immediate inspection.

CSV can be loaded by pandas without requiring the use of an openEO helper function, plotting is then also similar.

**Comment by Pratichhya** [comment]
changed the data download format in this specific file
